- name: "B-brawl-failed"
  color: "B60205"
- name: "B-brawl-merged"
  color: "5319E7"
- name: "B-brawl-merging"
  color: "006B75"
- name: "B-brawl-queued"
  color: "C2E0C6"
- name: "B-brawl-try"
  color: "FBCA04"
- name: "B-brawl-try-failed"
  color: "B60205"
- name: "bug"
  color: "d73a4a"
- name: "documentation"
  color: "0075ca"
- name: "duplicate"
  color: "cfd3d7"
- name: "enhancement"
  color: "a2eeef"
- name: "good first issue"
  color: "7057ff"
- name: "help wanted"
  color: "008672"
- name: "invalid"
  color: "e4e669"
- name: "question"
  color: "d876e3"
- name: "wontfix"
  color: "ffffff"
