#:schema node_modules/wrangler/config-schema.json
name = "email-worker"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
ENVIRONMENT = "development"
MAILGUN_MAILINGLIST = "website-landing@noreply.scuffle.cloud"
ALLOWED_ORIGIN_URLS = ''

[env.production]
name = "scuffle-landing-page-email-worker"
vars.ENVIRONMENT = "production"
vars.ALLOWED_ORIGIN_URLS='https://www.scuffle.cloud,https://scuffle.cloud'
vars.MAILGUN_MAILINGLIST = "website-landing@noreply.scuffle.cloud"
